[2025-08-26T19:12:25.965+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-26T19:12:25.990+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_data.generate_transaction_data manual__2025-08-26T19:12:24.977296+00:00 [queued]>
[2025-08-26T19:12:26.006+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_data.generate_transaction_data manual__2025-08-26T19:12:24.977296+00:00 [queued]>
[2025-08-26T19:12:26.006+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-08-26T19:12:26.042+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): generate_transaction_data> on 2025-08-26 19:12:24.977296+00:00
[2025-08-26T19:12:26.066+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'generate_data', 'generate_transaction_data', 'manual__2025-08-26T19:12:24.977296+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmpr2y5y14h']
[2025-08-26T19:12:26.074+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask generate_transaction_data
[2025-08-26T19:12:26.079+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-26T19:12:26.080+0000] {standard_task_runner.py:72} INFO - Started process 216 to run task
[2025-08-26T19:12:26.233+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_data.generate_transaction_data manual__2025-08-26T19:12:24.977296+00:00 [running]> on host a94bea4a24e8
[2025-08-26T19:12:26.819+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='generate_data' AIRFLOW_CTX_TASK_ID='generate_transaction_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T19:12:24.977296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-26T19:12:24.977296+00:00'
[2025-08-26T19:12:26.819+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-26T19:12:26.895+0000] {logging_mixin.py:190} INFO - Data generation complete.
[2025-08-26T19:12:26.895+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-08-26T19:12:26.904+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-26T19:12:26.904+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=generate_data, task_id=generate_transaction_data, run_id=manual__2025-08-26T19:12:24.977296+00:00, execution_date=20250826T191224, start_date=20250826T191225, end_date=20250826T191226
[2025-08-26T19:12:26.940+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-26T19:12:27.025+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-26T19:12:27.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
