[2025-08-27T00:00:02.664+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-27T00:00:02.680+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_data.generate_fraud_data scheduled__2025-08-26T00:00:00+00:00 [queued]>
[2025-08-27T00:00:02.687+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_data.generate_fraud_data scheduled__2025-08-26T00:00:00+00:00 [queued]>
[2025-08-27T00:00:02.687+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-08-27T00:00:02.700+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): generate_fraud_data> on 2025-08-26 00:00:00+00:00
[2025-08-27T00:00:02.709+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'generate_data', 'generate_fraud_data', 'scheduled__2025-08-26T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmp85pv_yeg']
[2025-08-27T00:00:02.712+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask generate_fraud_data
[2025-08-27T00:00:02.857+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=476) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-27T00:00:02.858+0000] {standard_task_runner.py:72} INFO - Started process 477 to run task
[2025-08-27T00:00:02.907+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_data.generate_fraud_data scheduled__2025-08-26T00:00:00+00:00 [running]> on host a94bea4a24e8
[2025-08-27T00:00:03.196+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='generate_data' AIRFLOW_CTX_TASK_ID='generate_fraud_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-26T00:00:00+00:00'
[2025-08-27T00:00:03.198+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-27T00:00:03.434+0000] {logging_mixin.py:190} INFO - Labeled transaction data inserted successfully.
[2025-08-27T00:00:03.435+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-08-27T00:00:03.442+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-27T00:00:03.443+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=generate_data, task_id=generate_fraud_data, run_id=scheduled__2025-08-26T00:00:00+00:00, execution_date=20250826T000000, start_date=20250827T000002, end_date=20250827T000003
[2025-08-27T00:00:03.482+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-27T00:00:03.494+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T00:00:03.495+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
